@startuml
title Navigation Diagram

[*] --> Login

Login --> Register : "Criar conta"
Register --> Login : "Registo concluído"

Login --> EndpointsList : "Login com sucesso"

EndpointsList --> EndpointDashboard : "Selecionar endpoint"
EndpointsList --> CreateMonitoring : "Criar monitorização"

CreateMonitoring --> EndpointsList : "Criado"

EndpointsList --> Login : "Logout"

@enduml