@startuml
title State Machine

[*] --> Unauthenticated

state Unauthenticated {
    state Login
    state Register
}

state Authenticated {
    state EndpointsList
    state EndpointDashboard
    state CreateMonitoring
}

Unauthenticated --> Authenticated : "Login sucesso"
Authenticated --> Unauthenticated : "Logout"

EndpointsList --> EndpointDashboard : "Selecionar endpoint"
EndpointsList --> CreateMonitoring : "Criar monitorização"

CreateMonitoring --> EndpointsList
EndpointDashboard --> EndpointsList

@enduml