# Complete requests

@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3RfaXNzdWVyIiwidXNlcklkIjoxLCJleHAiOjE3ODI3NzMxNjV9.-bpLYeXrSN1KbsCR9hJawFnXYWpXcvuONj9N3Iurjlw

###
GET {{baseUrl}}/metrics/agent
Content-Type: application/json
Accept: application/json

###
# Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "Admin12",
  "password": "Admin12"
}

###
# Login with the registered user
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Admin12",
  "password": "Admin12"
}

###
# Create a new endpoint monitor
POST {{baseUrl}}/endpoints
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "url": "https://example.com",
  "name": "ExampleTestAPI",
  "method": "GET",
  "intervalSeconds": 60,
  "notification": {
    "type": "discord_webhook",
    "webhookUrl" : "https://discord.com/api/webhooks/1501258756464316447/QwewEWmGGk830Pfy_NJz7XUsMMS8miqMowaUrtfC7SRpSWDyQ1c-Z8IUDmb6IkYhwd6V"
  },
  "alertRule": {
    "type": "status_code",
    "operator": "GTE",
    "value": 1,
    "durationSeconds": 120,
    "aggregation": {
        "type": "COUNT",
        "count": 1
    }
  }
}

###
# Create a new endpoint monitor
POST {{baseUrl}}/api/endpoints/create
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "url": "https://example2.com",
  "name": "Example2 Endpoint",
  "intervalSeconds": 120
}

###
# Get all endpoint being monitored
GET {{baseUrl}}/api/endpoints
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
# Delete an endpoint monitor
DELETE {{baseUrl}}/api/endpoints/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
# Get metrics for a certain endpoint
GET {{baseUrl}}/metrics/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



